### ISSUE TITLE
Happy Birthday!

### ISSUE THREAD

**Issue by nateinaction** [rohjay/aquaponics_pi#9]
![bitmoji](https://render.bitstrips.com/v2/cpanel/436bed32-ab83-4942-a5fb-a2b9066e00ed-f3cd80a8-11f2-46cc-abe1-8e78a31ff4c4-v1.png?transparent=1&palette=1&width=246)

**Comment by rohjay** [comment]
How am I just now seeing this?? Haha! Closing as irrelevant =P

Thanks brother =]
